[package]
name = "physics"
version = "0.1.0"
edition = "2021"

[dependencies]
# Use workspace dependencies
nalgebra = { workspace = true }
serde = { workspace = true }

# ECS dependency
ecs = { path = "../ecs" }